version: "3.7"
services:
  unsplash:
    build: .
    networks:
      - private
  ztsc:
    image: intelecy/ztsc:latest
    environment:
      - ZT_NETWORK_ID
    depends_on:
      - unsplash
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    devices:
      - /dev/net/tun
    init: true
    volumes:
      - ./identity.public:/var/lib/zerotier-one/identity.public:ro
      - ./identity.secret:/var/lib/zerotier-one/identity.secret:ro
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    networks:
      - private
networks:
  private:
